# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CropData_RestAPI', '0002_farms_wells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm_audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Farm_audio')),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Farm_Photos')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHold_audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='HouseHold_audio')),
                ('HouseHold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.HouseHolds')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHold_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='HouseHold_Photos')),
                ('HouseHold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.HouseHolds')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHolds_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Relation', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('HouseHold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.HouseHolds')),
            ],
        ),
        migrations.AddField(
            model_name='farms',
            name='HouseHold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.HouseHolds'),
        ),
        migrations.AddField(
            model_name='wells',
            name='Farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Farms'),
        ),
        migrations.AlterField(
            model_name='farms',
            name='TotalArea',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wells',
            name='Average_yield',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wells',
            name='Depth',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='farm_photos',
            name='Farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Farms'),
        ),
        migrations.AddField(
            model_name='farm_audio',
            name='Farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Farms'),
        ),
    ]
