# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 08:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CropData_RestAPI', '0004_households_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='households',
            name='position',
        ),
        migrations.AddField(
            model_name='households',
            name='Location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
