# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 08:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CropData_RestAPI', '0005_auto_20170815_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extent', models.FloatField()),
                ('Crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Well_Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yield', models.FloatField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='farm_audio',
            old_name='Image',
            new_name='Audio',
        ),
        migrations.RenameField(
            model_name='household_audio',
            old_name='Image',
            new_name='Audio',
        ),
        migrations.AddField(
            model_name='farms',
            name='Location',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='wells',
            name='Location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='well_yield',
            name='Farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Farms'),
        ),
        migrations.AddField(
            model_name='crop',
            name='Farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Farms'),
        ),
        migrations.AddField(
            model_name='crop',
            name='Season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropData_RestAPI.Season'),
        ),
    ]
